blueprint:
  name: Send a camera record to discord when motion is detected
  description: 'This automation blueprint creates a camera snapshot if motion is detected  and
    sends a notification with the screenshot.

    '
  domain: automation
  input:
    motion_sensor:
      name: Motion sensor
      description: The sensor wich triggers the snapshot creation
      selector:
        entity:
          domain:
          - binary_sensor
          device_class:
          - motion
          multiple: false
    camera:
      name: Camera
      description: The camera which creates the snapshot
      selector:
        entity:
          domain:
          - camera
          multiple: false
    notify_device:
      name: Device to notify
      description: Device needs to run the official Home Assistant app to receive
        notifications
      selector:
        device:
          integration: mobile_app
          multiple: false
    is_ios:
      name: Is it an iOS device?
      description: Toggle if your selected device runs iOS, default is Android
      selector:
        boolean: {}
      default: false
    notification_title:
      name: Notification title (Optional)
      description: 'Default: "Motion detected!"'
      default: Motion detected!
    notification_message:
      name: Notification message (Optional)
      description: 'Default: "{{ motion_sensor_name }} detected movement!"'
      default: '{{ motion_sensor_name }} detected movement!'
    delay:
      name: Delay (Optional)
      description: Wait before creating camera snapshot
      default: ''
      selector:
        number:
          min: 0.0
          max: 60.0
          unit_of_measurement: seconds
          mode: slider
          step: 1.0
    duration:
      name: Duration
      description: Duración prevista de la grabación. La duración real puede variar.
      default: ''
      selector:
        number:
          min: 0.0
          max: 60.0
          unit_of_measurement: seconds
          mode: slider
          step: 1.0
    lookback:
      name: Lookback (Optional)
      description: Período retrospectivo planificado para incluir en la grabación (además de la duración). Solo disponible si actualmente hay una transmisión HLS activa. La duración real del período retrospectivo puede variar.
      default: ''
      selector:
        number:
          min: 0.0
          max: 60.0
          unit_of_measurement: seconds
          mode: slider
          step: 1.0
  source_url: https://github.com/sabinico/ha-blueprints/blob/main/camera_record_on_motion.yml
trigger:
  platform: state
  entity_id: !input motion_sensor
  from: 'off'
  to: 'on'
variables:
  motion_sensor: !input motion_sensor
  motion_sensor_name: '{{ states[motion_sensor].name }}'
  camera: !input camera
  camera_name: '{{ states[camera].name }}'
  notify_device: !input notify_device
  is_ios: !input is_ios
  notification_title: !input notification_title
  notification_message: !input notification_message
  delay: !input delay
  duration: !input duration
  lookback: !input lookback
  snapshot_create_file_path: /config/www/tmp/snapshot_{{ states[camera].object_id
    }}.mp4
  snapshot_access_file_path: '{{ snapshot_create_file_path | replace(''/config/www'',''/local'')
    }}'
action:
- delay: '{{ delay }}'
- service: camera.record
  entity_id: !input camera
  data:
    filename: '{{ snapshot_create_file_path }}'
    duration: '{{ duration }}'
    lookback: '{{ lookback }}'
- device_id: !input notify_device
  domain: mobile_app
  type: notify
  title: '{{ notification_title }}'
  message: '{{ notification_message }}'
  data: '{% set android_data = {"image": "%s"} | format(snapshot_access_file_path)
    %} {% set ios_data = {"attachment": {"url": "%s", "content_type": "JPEG"}} | format(snapshot_access_file_path)
    %} {{ ios_data if is_ios else android_data }}

    '
- service: notify.sabi_home
  data:
    message: ''
    target:
    - '141550930465259520'
    - '1135288079637303316'
    data:
      images:
      - "{{ snapshot_create_file_path }}"
      embed:
        title: Motion Detected
        description: Se ha detectado movimiento en {{ motion_sensor_name }}
        url: https://my.home-assistant.io/
        color: 15816278
        author:
          name: Sabi Home Assistant
          url: https://my.home-assistant.io/
          icon_url: https://www.home-assistant.io/images/favicon-192x192-full.png
        footer:
          text: Generated from {{ camera_name }} at {{ states('sensor.date_time_iso')
            }}
          icon_url: https://www.home-assistant.io/images/favicon-192x192-full.png
        thumbnail:
          url: https://www.home-assistant.io/images/favicon-192x192-full.png
